server:
  port: 1234

springbootstart-sanytruck-paycenter:
  access:
    enable: true
    channel_code: PAY1010
    secret_key_path: D:/development/gitlab/demo/src/main/resources/nopaycenterkey/PAY1010
    access_url: "https://uat-pay.31truck.com/api/pay/v1/publicFunction/ticket"
    baseinfo_url: "https://uat-pay.31truck.com/api/pay/v1/publicFunction/baseinfo"
  commission:
    commission_url: "https://uat-pay.31truck.com/api/pay/v1/commission/submit"
    search_commission_url: "https://uat-pay.31truck.com/api/pay/v1/commission/search"
  consume:
    consume_url:
    refund_url:
    search_consume_url:
  account:
    open_person_account_url:
    query_person_account_url:
    open_company_account_url:
    query_company_account_url:
